name: Version Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to process'
        required: true
        type: string

jobs:
  process-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      id-token: write
      repository: write 
    steps:
      - name: Store version in repository variable
        env:
          MY_VERSION: ${{ github.event.inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$MY_VERSION" | gh variable set WORKFLOW_VERSION --repo="${{ github.repository }}"
        shell: bash
