name: Version Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to process'
        required: true
        type: string

jobs:
  process-version:
    runs-on: ubuntu-latest
    steps:
      - name: Store version in repository variable
        env:
          MY_VERSION: ${{ github.event.inputs.version }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "$MY_VERSION" | gh variable set WORKFLOW_VERSION --repo="${{ github.repository }}" --token="$PAT_TOKEN"
        shell: bash
