name: Version Dispatch Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to process'
        required: true
        type: string

jobs:
  process-version:
    runs-on: ubuntu-latest
    steps:
      - name: Store version in repository variable
        env:
          MY_VERSION: ${{ github.event.inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "VERSION=$MY_VERSION" >> $GITHUB_ENV
          gh variable set WORKFLOW_VERSION "$MY_VERSION" --repo ${{ github.repository }}
        shell: bash
